In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import json

In [4]:
df = pd.read_csv("C:/Users/SHREYA/Downloads/India_Crime - Copy_2/India_Crime - Copy/01_District_wise_crimes_committed_IPC_2001_2012.csv"
)

df.head()

,STATE/UT,DISTRICT,YEAR,MURDER,ATTEMPT TO MURDER,CULPABLE HOMICIDE NOT AMOUNTING TO MURDER,RAPE,CUSTODIAL RAPE,OTHER RAPE,KIDNAPPING & ABDUCTION,...,ARSON,HURT/GREVIOUS HURT,DOWRY DEATHS,ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY,INSULT TO MODESTY OF WOMEN,CRUELTY BY HUSBAND OR HIS RELATIVES,IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES,CAUSING DEATH BY NEGLIGENCE,OTHER IPC CRIMES,TOTAL IPC CRIMES
0,ANDHRA PRADESH,ADILABAD,2001,101,60,17,50,0,50,46,...,30,1131,16,149,34,175,0,181,1518,4154
1,ANDHRA PRADESH,ANANTAPUR,2001,151,125,1,23,0,23,53,...,69,1543,7,118,24,154,0,270,754,4125
2,ANDHRA PRADESH,CHITTOOR,2001,101,57,2,27,0,27,59,...,38,2088,14,112,83,186,0,404,1262,5818
3,ANDHRA PRADESH,CUDDAPAH,2001,80,53,1,20,0,20,25,...,23,795,17,126,38,57,0,233,1181,3140
4,ANDHRA PRADESH,EAST GODAVARI,2001,82,67,1,23,0,23,49,...,41,1244,12,109,58,247,0,431,2313,6507

In [5]:
print(df.columns)

Index(['STATE/UT', 'DISTRICT', 'YEAR', 'MURDER', 'ATTEMPT TO MURDER',
       'CULPABLE HOMICIDE NOT AMOUNTING TO MURDER', 'RAPE', 'CUSTODIAL RAPE',
       'OTHER RAPE', 'KIDNAPPING & ABDUCTION',
       'KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS',
       'KIDNAPPING AND ABDUCTION OF OTHERS', 'DACOITY',
       'PREPARATION AND ASSEMBLY FOR DACOITY', 'ROBBERY', 'BURGLARY', 'THEFT',
       'AUTO THEFT', 'OTHER THEFT', 'RIOTS', 'CRIMINAL BREACH OF TRUST',
       'CHEATING', 'COUNTERFIETING', 'ARSON', 'HURT/GREVIOUS HURT',
       'DOWRY DEATHS', 'ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY',
       'INSULT TO MODESTY OF WOMEN', 'CRUELTY BY HUSBAND OR HIS RELATIVES',
       'IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES',
       'CAUSING DEATH BY NEGLIGENCE', 'OTHER IPC CRIMES', 'TOTAL IPC CRIMES'],
      dtype='str')

In [6]:
yearly_crime = (
    df.groupby("YEAR")["TOTAL IPC CRIMES"]
    .sum()
    .reset_index()
)

yearly_crime

    YEAR  TOTAL IPC CRIMES
0   2001           3538616
1   2002           3560660
2   2003           3432240
3   2004           3664020
4   2005           3645204
5   2006           3756586
6   2007           3979346
7   2008           4186758
8   2009           4242690
9   2010           4449662
10  2011           4651150
11  2012           4774376

In [7]:
state_crime = (
    df.groupby("STATE/UT")["TOTAL IPC CRIMES"]
    .sum()
    .sort_values(ascending=False)
    .head(10)
    .reset_index()
)

state_crime

         STATE/UT  TOTAL IPC CRIMES
0  MADHYA PRADESH           4827540
1     MAHARASHTRA           4546872
2      TAMIL NADU           4120352
3  ANDHRA PRADESH           4037962
4   UTTAR PRADESH           3716148
5       RAJASTHAN           3711832
6       KARNATAKA           2962126
7          KERALA           2874918
8         GUJARAT           2771550
9           BIHAR           2692586

In [8]:
scatter_data = df[["MURDER", "THEFT"]].dropna()

scatter_data.head()

   MURDER  THEFT
0     101    199
1     151    366
2     101    723
3      80    173
4      82   1021

In [9]:
hist_data = df["TOTAL IPC CRIMES"].dropna()

hist_data.head()

0    4154
1    4125
2    5818
3    3140
4    6507
Name: TOTAL IPC CRIMES, dtype: int64

In [10]:
violin_data = df[
    ["STATE/UT", "TOTAL IPC CRIMES"]
].dropna()

violin_data.head()

         STATE/UT  TOTAL IPC CRIMES
0  ANDHRA PRADESH              4154
1  ANDHRA PRADESH              4125
2  ANDHRA PRADESH              5818
3  ANDHRA PRADESH              3140
4  ANDHRA PRADESH              6507

In [11]:
dashboard_visuals = {
    "yearly_crime": yearly_crime.to_dict(orient="records"),

    "state_crime": state_crime.to_dict(orient="records"),

    "scatter_data": scatter_data.to_dict(orient="records"),

    "hist_data": hist_data.tolist(),

    "violin_data": violin_data.to_dict(orient="records"),
}

In [12]:
with open(
    "../frontend/src/data/dashboard_visuals.json",
    "w"
) as f:
    json.dump(dashboard_visuals, f)

print("dashboard_visuals.json created successfully")

dashboard_visuals.json created successfully